### ISSUE TITLE
sa login disabled and SQL auth disabled in sql17d vagrant box

### ISSUE THREAD

**Issue by ryan-chadwick-fei** [gusztavvargadr/packer#104]
https://app.vagrantup.com/gusztavvargadr/boxes/w16s-sql17d

The documentation for the above box notes access to SQL via the local windows admin account 'vagrant' as well as the default SQL admin account 'sa'.

After bringing up the box the initial configuration for the SQL instances has 'sa' disabled and SQL logins disabled.  The password is also not set as noted: 'Vagrant42'.

**Comment by gusztavvargadr** [comment]
@ryan-chadwick-fei thanks for the feedback and sorry for the issue. I'll take a look and get back to you. There is a release planned within a couple of days, I will try to publish a fix for this as well.

**Comment by gusztavvargadr** [comment]
@ryan-chadwick-fei I confirm the issue, a fix is on the way, sorry again for the inconvenience.

I suggest to watch the repo so you get an update when the release is done.

**Comment by gusztavvargadr** [comment]
@ryan-chadwick-fei new releases are available now:

https://app.vagrantup.com/gusztavvargadr/boxes/w16s-sql17d
https://app.vagrantup.com/gusztavvargadr/boxes/w16s-sql14d

Could you please confirm it works as expected? Thanks for the patience :)
