### ISSUE TITLE
Virtualbox Windows images need to have Virtio network driver

### ISSUE THREAD

**Issue by diwu1989** [gusztavvargadr/packer#111]
Please install https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso in the Windows VM.

This will resolve the issue seen in https://github.com/gusztavvargadr/packer/issues/72

**Comment by StefanScherer** [comment]
I had the problem with one of my boxes with one specific Win10+VirtualBo 5.2 machine.  No network device found in the Win10 VM. 
On a MacBook and another Win10 host the same box works just fine without any change in the box or Vagrantfile.

**Comment by gusztavvargadr** [comment]
@StefanScherer thanks heaps for the information. Maybe something to do with the host OS / Vagrant version, VirtualBox (patch) version, and the guest additions constellation? I remember some issues earlier (maybe with VirtualBox 5.1) when there were several regressions across the patch versions.

Anyway, @diwu1989 if you let me know which Windows box you're working with, I can try to build a test version with the above package you mention.

**Comment by gusztavvargadr** [comment]
@diwu1989 can this be also the root cause? https://github.com/hashicorp/vagrant/issues/10448

Can you please try with the latest Vagrant (2.2.2) where it is supposed to be fixed?

**Comment by diwu1989** [comment]
I was using gusztavvargadr/w10e
And yes with 2.2.2 it fixes it.
The virtio driver is fairly small, it would be a good preventive measure to have it installed in case they decide to switch it to be the default again. It does theoretically have better performance.

**Comment by gusztavvargadr** [comment]
@diwu1989 thanks for getting back on this and for the update. Good to hear it's resolved now.

I agree, there are too many regressions (both for Vagrant and VirtualBox). I try to include this in the next release, to be expected later this month, after the major patches for the OSes ;)

**Comment by gusztavvargadr** [comment]
@diwu1989 I have now some new core OS images with the drivers included.

https://app.vagrantup.com/gusztavvargadr/boxes/windows-10
https://app.vagrantup.com/gusztavvargadr/boxes/windows-server

I will publish an update to rest of the boxes soon.
