### ISSUE TITLE
Running on Mac vagrant up hangs and I get the following output

### ISSUE THREAD

**Issue by tamirble** [gusztavvargadr/packer#114]
**vagrant up**
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'gusztavvargadr/w16s' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'gusztavvargadr/w16s'
    default: URL: https://vagrantcloud.com/gusztavvargadr/w16s
==> default: Adding box 'gusztavvargadr/w16s' (v1811.0.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/gusztavvargadr/boxes/w16s/versions/1811.0.0/providers/virtualbox.box
    default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> default: Successfully added box 'gusztavvargadr/w16s' (v1811.0.0) for 'virtualbox'!
==> default: Importing base box 'gusztavvargadr/w16s'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'gusztavvargadr/w16s' is up to date...
==> default: Setting the name of the VM: gusztavvargadr-w16s_default_1544523666686_69004
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 33389 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
--------
What can I do in order to make it work?

**Comment by gusztavvargadr** [comment]
@tamirble it might be related to #111.

Can you please let me know your host OS, Vagrant and VirtualBox version and update to Vagrant 2.2.2 and VirtualBox 5.2.22 if you're not running on the latest and test with those as well?

**Comment by gusztavvargadr** [comment]
@tamirble the new boxes now at https://app.vagrantup.com/gusztavvargadr/boxes/windows-server should have a workaround. Please see #111 as well for more details.
