### ISSUE TITLE
Hyper-V VMCX Builder configuration - typo in clone_from_vmcx_path

### ISSUE THREAD

**Issue by gursharan001** [gusztavvargadr/packer#116]
Refer https://www.packer.io/docs/builders/hyperv-vmcx.html#required-for-virtual-machine-import-

Correct configuration variable name is `clone_from_vmcx_path`
This was fixed in 1.3.0 packer release. Refer pull request https://github.com/hashicorp/packer/pull/6393 at https://github.com/hashicorp/packer/pull/6393/files#diff-5e38be1dcde30fabadff899cae9c4ee5L138

**Comment by gusztavvargadr** [comment]
@gursharan001 thanks for the issue as well, fyi, i fixed some broken links.
