### ISSUE TITLE
[Windows 10] - VM is rebooting

### ISSUE THREAD

**Issue by jacquecosta** [gusztavvargadr/packer#143]
My objective is to use vagrant to run GUI and Web automated tests in a CI.

When I start to run my tests using sikulix and serenitybdd usign the last windows box, the VM automatically reboot.

Any idea of what could be happening?

**Comment by gusztavvargadr** [comment]
@jacquecosta I'm not really sure.

The box contains a sysprepped version, so it reboots, but only once, and before WinRM comes up and Vagrant reports it booted. Do you have maybe a `vagrant up` log and any details on how you provision it afterwards?

Can you maybe try to reproduce with https://app.vagrantup.com/gusztavvargadr/boxes/windows-server instead of Windows 10 as well?

**Comment by jacquecosta** [comment]
@gusztavvargadr 

Testing with windows-server I got the same result as Windows 10, the VM is rebooting when running the tests.

The only information of `vagrant up --debug` is:

> DEBUG winrmshell: [WinRM] Waiting for output...
> DEBUG winrmshell: [WinRM] Processing output
> DEBUG winrmshell: [WinRM] Waiting for output...
> DEBUG winrmshell: [WinRM] cleaning up command_id: XXX  on shell_id XXX
> ERROR warden: Error occurred: An authorization error occurred while connecting to WinRM.
> 
> User: vagrant
> Endpoint: http://127.0.0.1:55985/wsman
> Message: WinRM::WinRMAuthorizationError
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: An authorization error occurred while connecting to WinRM.

**Comment by gusztavvargadr** [comment]
@jacquecosta can you maybe try to share a Vagrant configuration that I can use to reproduce this on my end?

**Comment by jacquecosta** [comment]
@gusztavvargadr 

I created a sample project with sikulix and serenitybdd to simulate the problem. In my machine, the windows box still rebooting when tests starts.

[testvagrant.zip](https://github.com/gusztavvargadr/packer/files/3637465/testvagrant.zip)

**Comment by gusztavvargadr** [comment]
@jacquecosta thanks for the test setup, I can confirm the issue on my end (Windows 10 latest host with latest VirtualBox). The last provisioner causes the machine to crash (not a simple reboot :) I try to look into a bit more detail and will get back to you asap.

**Comment by gusztavvargadr** [comment]
@jacquecosta I tried a couple of modifications in the VirtualBox image, but no luck yet, the machine still crashes upon the test starting.

However, when trying the same setup with Hyper-V, it executes correctly (the test case fails, but the provisioning completes without problem and Vagrant exits correctly).

I have less experience with the workload you have here, but I'd try changing the default VirtualBox hardware configuration Vagrant sets up. What is your host environment (OS, VirtualBox version) if I may ask?

**Comment by jacquecosta** [comment]
@gusztavvargadr 

I tested with:
- Vagrant 2.2.5 
- Virtualbox 6.0.10 and 6.0.12

- Vagrant 2.2.0
- Virtualbox 5.x

Using Linux (Ubuntu 18.04) and Windows 10 (Without Hyper-V support)

I hope exists a solution for that, I've tested with https://github.com/StefanScherer/packer-windows too but also crash.

**Comment by gusztavvargadr** [comment]
@jacquecosta I'm testing atm with different VirtualBox Guest Additions versions and trying various machine parameters with VirtualBox like display parameters / drivers.

The difference between the Hyper-V and VirtualBox boxes for the same OS I publish are only that, the guest additions and the [virtIO drivers](https://chocolatey.org/packages/virtio-drivers).

After the machine crashes when the test starts to execute, upon the next boot the event log in the guest contains events about the issue. To me it seems an issue with VirtualBox itself, but could not figure out yet what exactly is causing it.

**Comment by gusztavvargadr** [comment]
@jacquecosta Seems like updating the Guest Additions to latest 6.0.12 might resolve the problem, I am preparing a box for you so you can test with it as well (I was planning a release with the latest updates anyway).

**Comment by gusztavvargadr** [comment]
@jacquecosta I have published a [new version](https://app.vagrantup.com/gusztavvargadr/boxes/windows-10/versions/1903.0.1909-enterprise-143) dedicated for this case only, you can force this with the following line in your `Vagrantfile`:

```
config.vm.box_version = "1903.0.1909-enterprise-143"
```

With this the provisioning completes on my end without a crash, can you please check if it works for you as well?

```
    default: [INFO] current_project.base.dir: C:\vagrant
    default: [INFO] Generating test results for 1 tests
    default: [INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.PackageRequirementsTagProvider@2e4ecdf8, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@69a90b81]
    default: [INFO] LOADED REQUIREMENTS:
    default: REQUIREMENTS:
    default:     - feature : Acess website {id: acess-website, displayName: 'Acess website', path: feature_bug.feature, parent: 'null'}
    default: [INFO] 1 requirements loaded after 186 ms
    default: [INFO] 1 related requirements found after 202 ms
    default: [INFO] Generating test outcome reports: false
    default: [INFO] Starting generating reports after 333 ms
    default: [INFO] Configured report threads: 15
    default: [INFO] Test results for 1 tests generated in 2.2 secs
    default: [INFO]
    default: [INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ teste ---
    default: [WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
    default: [INFO] ------------------------------------------------------------------------
    default: [INFO] BUILD FAILURE
    default: [INFO] ------------------------------------------------------------------------
    default: [INFO] Total time:  01:58 min
    default: [INFO] Finished at: 2019-09-21T12:51:04Z
    default: [INFO] ------------------------------------------------------------------------
    default: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project teste: There are test failures.
    default: [ERROR]
    default: [ERROR] Please refer to C:\vagrant\target\failsafe-reports for the individual test results.
    default: [ERROR] -> [Help 1]
    default: [ERROR]
    default: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    default: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    default: [ERROR]
    default: [ERROR] For more information about the errors and possible solutions, please read the following articles:
    default: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
    default: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    default: SLF4J: Defaulting to no-operation (NOP) logger implementation
    default: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    default: Sep 21, 2019 12:50:29 PM org.openqa.selenium.remote.DesiredCapabilities chrome
    default: INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
    default: Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 19270
    default: Only local connections are allowed.
    default: Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
    default: [1569070235.514][WARNING]: Timed out connecting to Chrome, retrying...
    default: Sep 21, 2019 12:50:37 PM org.openqa.selenium.remote.ProtocolHandshake createSession
    default: INFO: Detected dialect: W3C
```

**Comment by jacquecosta** [comment]
@gusztavvargadr 

Thanks for your reply, testing with 

`config.vm.box_version = "1903.0.1909-enterprise-143"`

It has worked as expected! I will use this version per while. 

Just a doubt, maybe next releases will be with this fix too?

**Comment by gusztavvargadr** [comment]
@jacquecosta glad to hear it worked :) Thanks for the patience and the help with the debugging.

Indeed, I'm building the new release versions atm, once it's done, I'll publish `1903.0.1909` and will delete the current temporary version, I'll let you know.

**Comment by jacquecosta** [comment]
@gusztavvargadr  I am glad with your responses.

I am using the box "1903.0.1909-enterprise-143", but the max resolution screen is small for my GUI tests, do you know a way to increase the resolution?

**Comment by gusztavvargadr** [comment]
@jacquecosta this is what I've found: https://blog.jamesbayley.com/2016/02/10/fixed-tiny-screen-in-virtualbox-guest/

You can try them applying from the Vagrantfile directly as well: https://www.vagrantup.com/docs/virtualbox/configuration.html#vboxmanage-customizations

Let me know if it helps!

**Comment by gusztavvargadr** [comment]
@jacquecosta FYI there is now a new default [public version](https://app.vagrantup.com/gusztavvargadr/boxes/windows-10/versions/1903.0.1909) that should contain the latest fixes. Can you please try reverting to not specifying a version number, and test that it works with `1903.0.1909` as well?

**Comment by jacquecosta** [comment]
@gusztavvargadr 
Tested with new public version and everything worked!

About changing screen resolution, today I got this working, using:

```
vb.customize ["modifyvm", :id, "--vram", "256"]
vb.customize ["setextradata", :id, "GUI/MaxGuestResolution", "1280x1024x32"]
vb.customize ["setextradata", :id, "CustomVideoMode1", "1280x1024x32"]
vb.customize 'post-boot', ["controlvm", :id, "setvideomodehint", "1280", "1024", "32"]
```

**Comment by gusztavvargadr** [comment]
@jacquecosta great news, thanks for sharing the results about the resolution test, might be useful for others as well :)

I'm closing this now but please let me know if you have any other feedback later.
