### ISSUE TITLE
config.ssh.username and config.ssh.password not working

### ISSUE THREAD

**Issue by blkwtch** [gusztavvargadr/packer#157]
v1.3.8 
Hi
not sure why but it seems that the box doesn't consider the password parameter from the vagrant file...
also, does the box come with a default login/password combo?
thank you

**Comment by blkwtch** [comment]
![image](https://user-images.githubusercontent.com/23279025/67487378-158e6600-f66e-11e9-9971-4e65252ab0bb.png)

**Comment by gusztavvargadr** [comment]
@blkwtch this is not my box, you can maybe try at https://github.com/YungSang/coreos-packer?

**Comment by gusztavvargadr** [comment]
@blkwtch I'm closing this but please reopen if you have any feedback regarding the boxes of this repo.
