### ISSUE TITLE
GuestAdditions versions on your host (6.1.2) and guest (6.0.14) do not match.

### ISSUE THREAD

**Issue by bladesaunterer** [gusztavvargadr/packer#170]
After upgrading to virtual box 6.1.2 and vagrant 2.2.7, the Guest Additions version and the virtual box version aren't in line. 
```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.14
VBoxService inside the vm claims: 6.1.2
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.14
VBoxService inside the vm claims: 6.1.2
Going on, assuming VBoxService is correct...
```

Everything as far as I can tell is still working though :)

**Comment by gusztavvargadr** [comment]
Hi @bladesaunterer thanks for reporting this. I'm yet to build and publish new versions with VirtualBox 6.1.2, which will hopefully solve this. In the meantime you can try manually updating the guest additions inside the VM and check of the warning disappears.

Btw which box are you using and what is your host configuration?

**Comment by gusztavvargadr** [comment]
@bladesaunterer I have published new versions for most of the boxes with VirtualBox 6.1.4, using the latest Vagrant 2.2.7 this should now work, please let me know.

**Comment by gusztavvargadr** [comment]
@bladesaunterer I'm closing this but please feel free to reopen if you have any further questions.
