### ISSUE TITLE
Add images based on Windows 10 LTSC

### ISSUE THREAD

**Issue by doman18** [gusztavvargadr/packer#184]
Windows 10 LTSC (Long-Term Servicing Channel ) is a Enterprise version targeted to systems where stability and reliability are far more important than new features. It is shipped without Cortana, Windows Store, OneNote and similar things. Only critical updates are downloaded and feature updates are merged every 3 years.

**Comment by gusztavvargadr** [comment]
@doman18 thank you for the suggestion, I'm planning next release to add this and other variants (like the insider previews).

May I ask what other boxes do you use besides the core Windows 10 one?

**Comment by gusztavvargadr** [comment]
@doman18 here's a base image for the OS itself, can you please take a look and let me know if it's what you expected?

https://app.vagrantup.com/gusztavvargadr/boxes/windows-10-1809-enterprise-ltsc

**Comment by gusztavvargadr** [comment]
@doman18 there's a proper published version now, please let me know if you have any feedback.

https://app.vagrantup.com/gusztavvargadr/boxes/windows-10-1809-enterprise-ltsc
