### ISSUE TITLE
Use gitbash or power shell when using vagrant ssh

### ISSUE THREAD

**Issue by Bnaya** [gusztavvargadr/packer#190]
Is there a way to configure that the remote shell will be gitbash or powershell?
Thanks!

**Comment by gusztavvargadr** [comment]
@Bnaya afaik this is an OpenSSH setting and I simply use the default for now. Please take a look at https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration#configuring-the-default-shell-for-openssh-in-windows for more details.

Would you prefer changing this to e.g. PowerShell by default? I'm about to give the vagrant winssh a new try, earlier versions it was not working for me.
