### ISSUE TITLE
Only boot up successfully with default config

### ISSUE THREAD

**Issue by wsszh** [gusztavvargadr/packer#234]
Hi, I want to say thanks for making these, very helpful! But I have some trouble booting the VM.
I can successfully boot up the VM with default config(1 vCPU and 1GB of RAM). However, if I try more vCPU in Vagrantfile, I can not boot up the same VM, it hangs out on the splash screen every time I tried. Please help me:(

Some info:

- Host OS: Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
- Vagrant version: 2.2.9
- Virtualbox version: 6.1.12 r139181
- Vagrant box: gusztavvargadr/windows-server
- Vagrant box version: 1607.0.2006.standard-core

Here is my Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

opts = {
      :name => "winserver-test",
      :vm_name => "winserver-test",
      :box_name => "gusztavvargadr/windows-server",
      :box_version => "1607.0.2006.standard-core",
      :mem => "2048",
      :cpu => "2",
}

Vagrant.configure("2") do |config|
  config.vm.box = opts[:box_name]
  config.vm.box_version = opts[:box_version]
  config.vm.network "private_network", type: "dhcp"
  config.vm.boot_timeout = 1200

  config.vm.define opts[:name] do |demo|
    demo.vm.hostname = opts[:name]

    demo.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", opts[:mem]]
      v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      v.name = opts[:vm_name]
    end
  end
end

```

**Comment by gusztavvargadr** [comment]
@wsszh thanks for reaching out and glad to hear you find these useful!

A couple of hints and suggestions:

- Please try to use the latest version of Vagrant available at https://www.vagrantup.com/downloads.html
- You can do a simpler config for adjusting the memory and CPU values https://github.com/gusztavvargadr/packer/blob/0cc6c318f4bda2d048f7741baf36b3a0242c08c0/src/w/packer/postprocessors/vagrant-virtualbox/Vagrantfile#L9-L10
- Please try to use the latest version of the boxes. There's a dedicated box for Windows Server Standard Core, which can make your config simpler at https://app.vagrantup.com/gusztavvargadr/boxes/windows-server-standard-core. You can use `config.vm.box_version ~> '1607'`
 for the lastest 2016 release and `config.vm.box_version ~> '1809'` for the latest 2019 one.
- Please use the version of VirtualBox that matches the guest additions version the box. You can find it at the version description.
  - For the version you used it's `6.1.10`.
  - For the latest version it's currently `6.1.14`.
- Please note that changing the hostname results in an additional reboot on Windows when creating the machine, so wait times can be longer.

For better debugging please share the screenshot where you see the issue, I'm not sure which splash screen you mean exactly). Also, you can try running Vagrant with debugging enabled (e.g. `vagrant up --debug`) and uploading your log, that could be a lot of help to diagnose this. https://www.vagrantup.com/docs/other/debugging

**Comment by wsszh** [comment]
@gusztavvargadr After much searching and trying, I finally solved the problem. It turns out that although Virtualbox and Hyper-V can coexist now, Hyper-V still has negative effect on Virtulbox VMs. Thanks for your help!!!

**Comment by gusztavvargadr** [comment]
@wsszh thanks for the heads-up, glad that it works. Let me know if there's anything else I can help with.
