### ISSUE TITLE
An error occurred executing a remote WinRM command

### ISSUE THREAD

**Issue by zishiguo** [gusztavvargadr/packer#246]
vagrant version 2.2.15
run `vagrant up`, error as follow

`
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'gusztavvargadr/windows-10'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'gusztavvargadr/windows-10' version '2009.0.2012' is up to date...
==> default: Setting the name of the VM: win10_default_1617350991927_89384
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 33389 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
An error occurred executing a remote WinRM command.

Shell: Cmd
Command: hostname
Message: Unable to parse authorization header. Headers: {"Connection"=>"close", "Proxy-Connection"=>"close", "Content-Length"=>"0"}
Body:  (503).
`

**Comment by zishiguo** [comment]
I find reason. because of terminal set proxy

**Comment by gusztavvargadr** [comment]
@zishiguo good that you found a workaround. If you think, please add the details of how to resolve it, so others facing the same issue can fix it as well efficiently 👍

**Comment by mahmoud-ashi** [comment]
I faced the same issue with vagrant 2.2.15 on ubuntu. All I did is unset the proxies. For example
```
export http_proxy=
export https_proxy=
export no_proxy=
```
