### ISSUE TITLE
[Windows-10 Vagrant] Windows 10 Vagrant Box Times out

### ISSUE THREAD

**Issue by peasead** [gusztavvargadr/packer#276]
First off, thank you for providing these images. They're tremendously helpful.

I have noticed that with the Windows 10 Vagrant box, it will stall until a timeout unless I log into it. If I log into it, it proceeds and completes as expected.

It seems to just dump these to screen (when using `info` logging) until I log in. 

```
INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "5020d5b8-7199-4714-a715-0ad38ad78028", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
```

My info
```
 INFO global: Vagrant version: 2.2.18
 INFO global: Ruby version: 2.7.4
 INFO global: RubyGems version: 3.1.6
 INFO global: VAGRANT_LOG="info"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_INSTALLER_ENV="1"
```

[vagrant-info-log.log](https://github.com/gusztavvargadr/packer/files/7296341/gusztav-windows-vagrant.log)

I have a video of this in action if needed.

Thanks in advance.

**Comment by peasead** [comment]
I _think_ that if this was set to autologin, that'd get around this...but I think that's a Vagrant box thing vs. anything I can do with Vagrantfile.

**Comment by peasead** [comment]
Thanks for the response, @gusztavvargadr. If you use the Vagrantfile I have below with `VAGRANT_LOG=info vagrant up`, you don't have these timeouts?

The log file I shared above, but didn't describe properly, was highlighting the timeout and that if I logged in via VirtualBox, the machine continues to boot. Attached is the whole log of it timing out. [vagrant.log](https://github.com/gusztavvargadr/packer/files/7308264/vagrant.log). The timeout sequence starts at line `529` and ends at `1623-1625` with this error.

```
ERROR warden: Error occurred: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

That said, the machine is still running, but because it times out, Vagrant terminates prematurly, and any provisioning scripts fail to launch. I think that the machine needs to be configured to autologin with `vagrant:vagrant` so the machine continues to build.

My Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
end
```

As an example, when I use this Vagrantfile, it boots properly and completes as normal
```
Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_10"
end
```

I feel like no one else has opened an issue, so it certainly could be me.

**Comment by peasead** [comment]
I can take a video if it'd help...but if it's just me, then...it's just me :(

**Comment by gusztavvargadr** [comment]
@peasead @radicaljims thanks for confirming the issue, my bad, I was trying testing with an earlier version. I can also confirm this happens on my end, sorry for the inconvenience. Indeed, by default the boxes should do autologon, it is configured for all my boxes - because WinRM is enabled on the first logon -, but I notice that for some reason Windows Update kicks in, this might be that breaks the intended behavior.

I have just released a new version that should fix the issue: https://app.vagrantup.com/gusztavvargadr/boxes/windows-10/versions/2101.0.2109, it also contains the latest patches. I will also double check how the previous version could slip through my automated tests and try to improve the initial boot experience.

Can you try with this and let me know if it works now as expected?

**Comment by peasead** [comment]
Bingo, that worked.

```
vagrant box update
vagrant up
```

And you're right, there were some Windows updates that took place that caused a few reboots...that may have been it.

**Comment by markul** [comment]
Having the same issue with the visual-studio box, 'vagrant up' hangs on : 
> default: WinRM transport: negotiate
and then times out.

**Comment by gusztavvargadr** [comment]
@peasead thanks for confirming, glad to hear it works now.
