### ISSUE TITLE
Windows 10: Use Enterprise proper instead of Enterprise Evaluation

### ISSUE THREAD

**Issue by msarehn** [gusztavvargadr/packer#286]
We're using your Windows 10 images to automate the setup of a Windows Build VM for our CI (and it's been a real life-saver, thank you, a thousand times!)
Unfortunately, we cannot activate the Windows 10 VM, because it's the Enterprise Evaluation edition. Effectively, it's missing the SKUs in `C:\Windows\System32\spp\tokens\skus`. Copying the missing SKU information from a different Windows 10 version works, but that's quite a hack and I'm pretty sure that MS doesn't approve.

Could you add Windows 10 Enterprise (proper) instead of or in addition to the Evaluation version? Needs only the Enterprise install, even, because edition up- and downgrades can be done simply be using a differnt product key.

**Comment by gusztavvargadr** [comment]
@msarehn closing this now, but please let me know if there's anything else I can help with.

**Comment by msarehn** [comment]
@gusztavvargadr sorry, totally forgot to reply. Thanks for your help! Indeed, we're now building our own boxes, so everything's fine :-)
