### ISSUE TITLE
install windows vs issues 

### ISSUE THREAD

**Issue by systems1** [gusztavvargadr/packer#307]
wsl2 not included 
docker desktop doesnt work

WslRegisterDistribution failed with error: 0x80370102

https://github.com/microsoft/WSL/issues/7638

**Comment by gusztavvargadr** [comment]
@systems1 sorry, can you be a bit more specific?

What are you trying to do, what do you see and and what do you expect instead?

**Comment by systems1** [comment]
this was for windows-docker-desktop-visual-studio  image  to up with vagrant 
spin up using vagrant on windows 10
 
this did not work on windows 10 to use with vagrant 
docker doesnt start and wsl also not able to install

**Comment by gusztavvargadr** [comment]
@systems1 which provider are you using?

In case of Hyper-V (that's what I would assume if you're on Windows 10), can you try enabling virtualization extensions in your Vagrantfile?

https://www.vagrantup.com/docs/providers/hyperv/configuration#enable_virtualization_extensions

For VirtualBox, Docker Desktop will work only with Windows Containers, it is a limitation of the nested virtualization (Hyper-V inside VirtualBox does not work).

**Comment by systems1** [comment]
Im using local laptop windows 10 with virtualbox  ,already enabled virtualization on laptop
so this is only for server windows with hyper-v ?

**Comment by gusztavvargadr** [comment]
@systems1 you can run Hyper-V on Windows 10 with no problem, see the official docs for more details: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

That way you can also have WSL and Docker Desktop on your phyisical host, I'm not sure of the exact scenario you want to achieve. If you're just testing these, it's good to try them in a VM first, but they also work decently for regular workloads.

If you have other workloads with VirtualBox on the same host, that can have some issues, as it is currently experimental afaik to run VirtualBox with Hyper-V enabled, but you can try it as described here: https://www.how2shout.com/how-to/use-virtualbox-and-hyper-v-together-on-windows-10.html

In this case I'd recommend running only Linux-based workloads on VirtualBox, and WIndows-based ones on Hyper-V.

**Comment by gusztavvargadr** [comment]
@systems1 closing this now. Please reopen if you have further questions.
