### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by reben-f5** [gusztavvargadr/packer#308]
I am trying to install this win10 version but there seems to be a problem with, could you please review below and advise? Thanks for your help!

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'gusztavvargadr/windows-10' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'gusztavvargadr/windows-10'
    default: URL: https://vagrantcloud.com/gusztavvargadr/windows-10
==> default: Adding box 'gusztavvargadr/windows-10' (v2102.0.2112) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/gusztavvargadr/boxes/windows-10/versions/2102.0.2112/providers/virtualbox.box
    default:
    default: Calculating and comparing box checksum...
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x Vagrantfile
x box.ovf
x gusztavvargadr-w102102e-2112.0.0-1639836121-disk001.vmdk: Write failed
x metadata.json
bsdtar.EXE: Error exit delayed from previous errors.

**Comment by gusztavvargadr** [comment]
@reben-f5 Can you please double check if you have enough free disk space? To me the box download and unpackage works correctly, so the problem might be on your end.

**Comment by reben-f5** [comment]
Thanks @gusztavvargadr for your help, yes actually it is a problem with storage capacity that is nearly full which is unexpected from the machine. Thanks again !!!

**Comment by gusztavvargadr** [comment]
@reben-f5 good to hear you could isolate the problem. Closing this now, but please reopen and let me know if there's anything else I can help with.
