### ISSUE TITLE
virtualbox version of windows 10 cannot access through the rdp suddenly.

### ISSUE THREAD

**Issue by meteoricfarm** [gusztavvargadr/packer#361]
Thanks for your work, I could use the windows 10 box very useful.
But, suddenly it can't be connected through the RDP.
I can access RDP when I launch the virtual machine with the command below.
`vboxmanage startvm win10 --type=headless `
but, it can't be possible to access RDP when I use the command below.

> $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
    default: Adapter 3: bridged
==> default: Forwarding ports...
    default: 3389 (guest) => 53389 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/kids/workspace/vagrant/win10
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

is there any way to use vagrant properly?
If you need logs, please let me know.

**Comment by gusztavvargadr** [comment]
@meteoricfarm I am super sorry for the delay, had to take a break.

Are you still experiencing this? If possible, please share any details on your running environment so I can try to reproduce. Thanks!

**Comment by meteoricfarm** [comment]
Dear Gusztav,

Thanks for your reply and don't be sorry.
RDP is now working properly.
you don't have to follow up this issue.

Sincerely,
