### ISSUE TITLE
Add boxes for Ubuntu 2204

### ISSUE THREAD

**Issue by gusztavvargadr** [gusztavvargadr/packer#372]
### Summary

- [x] Server
- [x] Desktop
  - [x] Consider Ubuntu Desktop proper instead of Xfce

**Comment by maxkratz** [comment]
Thank you for your Vagrant images!
Is there any ETA for the build of Ubuntu Desktop xfce 22.04 images?

**Comment by gusztavvargadr** [comment]
@maxkratz thanks for your comment. I don't have an actual ETA at the moment, but will try to prioritize this.

Just curious, would you prefer xfce or the default Ubuntu Desktop? I was considering switching to make the latter the default but I can build multiple variants if needed.

Thanks!

**Comment by maxkratz** [comment]
> @maxkratz thanks for your comment. I don't have an actual ETA at the moment, but will try to prioritize this.

Thank you!

> Just curious, would you prefer xfce or the default Ubuntu Desktop? I was considering switching to make the latter the default but I can build multiple variants if needed.

I, personally, would prefer the xfce variant (because of the smaller size), but I think that most people would prefer the default Ubuntu desktop. Multiple variants would be nice.

**Comment by gusztavvargadr** [comment]
@maxkratz FYI, a couple of more Ubuntu boxes are now availabe, both Server and Desktop:

https://github.com/gusztavvargadr/packer/blob/aa2f7a9da918dd7728b99d0644a0feef4b38a7a4/README.md#ubuntu

Please let me know.

**Comment by maxkratz** [comment]
> Please let me know.

@gusztavvargadr Thank you very much. I've migrated our VM build CI to your [xubuntu-desktop-2204-lts](https://app.vagrantup.com/gusztavvargadr/boxes/xubuntu-desktop-2204-lts) box successfully.
