### ISSUE TITLE
Add more OS boxes without configuration management

### ISSUE THREAD

**Issue by gusztavvargadr** [gusztavvargadr/packer#374]
### Summary

- [x] Windows Server
- [x] Windows Server Core
- [x] Windows 11
- [x] Windows 10
- [x] Ubuntu Server
- [x] Ubuntu Desktop

### References

- Related to #296

**Comment by gusztavvargadr** [comment]
@JoelMiller74 @decoyjoe after having some issues with Chef 18.x, I was giving this some more thought and was considering making actually the `nocm` configuration the default for all my boxes, and hence deprecating the dedicated `nocm` boxes.

The only non-standard component in the boxes I'd like to keep is the SSH server as a Windows Feature. WinRM works, but file transfers are very slow, and SSH provides a lot of additional options like port forwarding, etc.

What would you guys think about having `nocm` as the default option? Would be a lot easier for me as well from a maintenance point of view.

**Comment by decoyjoe** [comment]
I would like to see that, the `nocm` box build being the default. I sometimes use these boxes for work outside of Test Kitchen (i.e. Chef) so the less that's pre-installed, the more versatile the boxes are. I do agree to keep the SSH server installed though.

If someone does want Chef installed it's as simple as running one `vagrant provision` command to install it:

```powershell
. { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -version 18
```

**Comment by gusztavvargadr** [comment]
@decoyjoe thanks for the feedback.

Yeah, indeed, although I use mainly Chef for provisioning by default - hence was this in the boxes in the first place -, it is relatively easy to install it, and would help squeeze at least the Windows Server boxes to keep under 5 GB in size (I noticed Vagrant Cloud throttles down the download speed for images larger than that).

Also, with Chef 18 I ran into issues, it does not seem to work by default after Sysprep, so I need to run a repair / reinstall anyway.

**Comment by decoyjoe** [comment]
> and would help squeeze at least the Windows Server boxes to keep under 5 GB in size (I noticed Vagrant Cloud throttles down the download speed for images larger than that).

Yes anything you could do to shrink the box size would also be great!

**Comment by gusztavvargadr** [comment]
@decoyjoe @JoelMiller74 FYI, starting from the 2312 release (which I am publishing now) all the boxes will default to not having Chef and other tools like Chocolatey on Windows installed by default.

This means the `nocm` versions will not add value anymore, so I am also deprecating those, and they will not receive any further updates. Please consider updating your configs to use the regular versions.

Thanks and please let me know.

**Comment by decoyjoe** [comment]
Fantastic, thanks for that work @gusztavvargadr!
