### ISSUE TITLE
GUI applications started from VBoxManage CLI are running in the vagrant on recent windows boxes

### ISSUE THREAD

**Issue by vmabille-intel** [gusztavvargadr/packer#383]
First of all thank you for your work in this repo, we're heavily relying on the boxes in this repo and they bring a lot of value to our work!

I've noticed a regression in the recently updated windows boxes. It seems that the way to launch GUI applications changed from older images, when the applications are started using the VBoxManage guestcontrol CLI command. 

For example, when opening notepad using the VBoxManage command:
`sudo VBoxManage --nologo guestcontrol <box_id> run --exe cmd.exe --username vagrant --password vagrant -- cmd /c notepad.exe`

On recent boxes (e.g. windows 10 v2202.0.2303) the notepad application starts in the background, and the notepad window doesn't get opened inside the VBox.
On older images (e.g. windows 10 v2101.0.2211), we see the notepad window getting opened in the VBox. 

As a consequence, this issue is preventing us from starting SWTBot GUI tests with maven from the host running the Vagrant box.   

Is this change of behavior actually expected? Is there something we could do about it?
I'm able to work around it by pinning our boxes to a specific version but this may be an issue in the future when we wish to update our images. 

Let me know if you need further information, 
thanks in advance!

**Comment by gusztavvargadr** [comment]
@vmabille-intel thanks for the kind words and feedback, glad to hear that you find the boxes useful, helps a lot with the motivation to keep building them :) Please keep sharing any feedback or suggestions you might have.

Sorry to hear about the issue with the recent versions. A significant change between the earlier and current versions is that for VirtualBox I have upgraded the guest additions to version 7.0 as that's now the current major version. Could you please check if your host VirtualBox version matches those of the boxes? Maybe you're on 6.1 or anything earlier that might affect this?

A possible way to confirm the issue would be that you downgrade the VirtualBox Guest Additions version in the box to match your host's VirtualBox version. Earlier versions can be downloaded from the [offical download page](https://www.virtualbox.org/wiki/Downloads).

Please let me know about your findings re these version (mis)matches so we can investigate further.

**Comment by vmabille-intel** [comment]
Thanks for the prompt reply, I was indeed using virtualbox 6.1 and vagrant 2.2.19.
I've updated my environment to use virtual box 7.0.6 and vagrant 2.3.4 but unfortunately I have the same results.

**Comment by gusztavvargadr** [comment]
Thanks for the update! What I would also try to run it with VirtualBox 6.1 on the host and downgrading manually the guest extension in the guest to the same 6.1 versiin. Just to rule out if it's a regression in VirtualBox itself.

Maybe the command's parameters have changed between 6.1 and 7.0 on the VirtualBox side?

**Comment by vmabille-intel** [comment]
Alright, let me try that as well. 
Could you though let me know how to set the guest extension to a specific version in a box?

**Comment by gusztavvargadr** [comment]
You can grab the guest additions as an ISO image for each version from the [downloads directory](https://download.virtualbox.org/virtualbox/) with the name `VBoxGuestAdditions_<version>.iso`.

It is a regular app in the guest, you can uninstall the current version via `Add / Remove Programs` and install the matching version after mounting the downloaded ISO and launching the installer. You might need a couple of reboots of the guest, but this should do it.

Thanks for helping with testing this, I cannot verify this right now myself, but please let me know if you run into any issues still and I will try to reproduce and find a workaround until then.

Btw, just curious, why are you controlling app runs via VBoxManage? Did you try via any provider-independent ways like regular provisioning in the Vagranfile?

**Comment by vmabille-intel** [comment]
Thanks for the details! 
I have to switch priorities for the next days/weeks so I'll have to delay the investigation, but this is definitely on my to-do list. I'll update you as soon as I can but I kindly ask for your patience :) 

On your question, we control the app using VBoxManage because we store the boxes on a server once they're provisioned, and download them to execute the tests inside. 
As the tests may change, and may run on different hosts, we keep our base images static to save some time on the building and provisioning part in our CI pipelines.

**Comment by vmabille-intel** [comment]
Hi Gusztáv, took me a while to get back to this but I eventually got the time for it :) 

So I downgraded the VBox Guest Additions in the windows image windows-10 v2202.0.2304 from 7.1.x to 6.1.40, and I can confirm that there is no issue anymore after doing this - Notepad gets opened when running the command `VBoxManage ... cmd /c notepad.exe` mentioned in the initial post. 
So it does seems that Virtualbox 7 introduced a breaking change, or require new parameters for the guestcontrol command... 
I could not find anything related in the Virtualbox 7 changelog though.

**Comment by gusztavvargadr** [comment]
@vmabille-intel fyi, just did some search around this on the VirtualBox forums and came across [this ticket](https://www.virtualbox.org/ticket/21230) which seems to confirm the issue on their end.

Until a fix is available I will consider reverting back my boxes to VirtualBox 6.1 by default, but will proceed with building some hotfixes as requested at #396.

**Comment by vmabille-intel** [comment]
@gusztavvargadr The issue in the ticket looks familiar indeed :) 
Okay, sounds good to me, thanks!

**Comment by gusztavvargadr** [comment]
I have reverted to the `6.1` branch for the guest additions in #396, closing this now.
