### ISSUE TITLE
C++ tooling

### ISSUE THREAD

**Issue by wighawag** [gusztavvargadr/packer#388]
Hey, just stamble on your vagrant boxes. These looks like a promising way to test out stuff on windows

I am using this vagrant box : https://app.vagrantup.com/gusztavvargadr/boxes/visual-studio-2022-community-windows-11/

and I would like to add c++ tools. I have a rust package that fails with `link.exe` missing

I tried the following:

```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community" --quiet --add Microsoft.VisualStudio.Workload.NativeDesktop
```

but it not seems to install anything

Any idea?

**Comment by gusztavvargadr** [comment]
@wighawag sorry for the delay, I did not have the time to look into this yet. Any luck maybe in the meantime?

**Comment by wighawag** [comment]
No worries, thanks for the message 
In the end i ended up using a manual install of windows on virtualbox using the iso distributed by microsoft and installed visual studio via the ui

**Comment by gusztavvargadr** [comment]
@wighawag ok, thanks for the update, good to hear that you've found a solution.

Feel free to use any of the [core OS boxes](https://app.vagrantup.com/gusztavvargadr) and install VS on top of that, or let me know if addtional VS workloads would make sense in the boxes by default, I am glad to extend them as well. A possible drawback would be the size of the hosted boxes, which is already nearing 20 GB.

If you're looking for a repeatable solution, an approach can be to customize the Packer builds and build your own image.
