### ISSUE TITLE
Request to add Windows boxes with VBox Guest Additions v6

### ISSUE THREAD

**Issue by vmabille-intel** [gusztavvargadr/packer#396]
Hi Gusztáv! 

I noticed that older Windows images got removed from your cloud over the weekend (e.g. https://app.vagrantup.com/gusztavvargadr/boxes/windows-10). 
Since we have an issue with newer images, which contain a VBox Guest Additions version 7 (https://github.com/gusztavvargadr/packer/issues/383), we were pinning our base images to the older versions that got removed. E.G.: 2102.0.2211 for the windows-10 box, and 1809.0.2211 for the windows-server-2019-standard box. 

Could I therefore kindly ask for either the re-upload of some of the older images that got removed, or to upload a few windows images which contain VBox Guest additions version 6? The windows version itself is for our projects not relevant.

**Comment by vmabille-intel** [comment]
Just updated our images and everything works well again, many thanks @gusztavvargadr

**Comment by gusztavvargadr** [comment]
@vmabille-intel that's great to hear, then I'll stick with the `6.1` for the time being and let's re-evaluate `7.0` again maybe after some stabilization period :)

Closing this issue now.
