### ISSUE TITLE
[Ubuntu 22] Change ssh-rsa key by ed25519

### ISSUE THREAD

**Issue by civodul999** [gusztavvargadr/packer#421]
Hi,
with this [vagrant box on Ubuntu 22](https://app.vagrantup.com/gusztavvargadr/boxes/ubuntu-desktop/versions/2204.0.2312), it's impossible to connect using ssh protocol.
Here the error message when I run `vagrant up`

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2201
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```
The box is created and visible on virtualbox, I can connect with the GUI.

Here the error message when I run `journalctl -f`

`userauth_pubkey : key type ssh-rsa not in PubkeyAcceptedAlgorithms`

On my computer, I see the default public key is generated with ssh-rsa type which is deprecated on ubuntu 22.04.

Is it possible to fix this in next version of vagrant box for Ubuntu 22 please ?

**Comment by gusztavvargadr** [comment]
@civodul999 thanks for reaching out and reporting the issue.

This seems to work for me just fine on my setup, [the build tests also passed](https://dev.azure.com/gusztavvargadr/packer/_build/results?buildId=10327&view=logs&j=71180a45-561b-5d94-a1ac-000ae7f529f2&t=e11713b9-ca3e-51e6-15bb-d5da95e3c60a).

Can you please share your OS, Vagrant and VirtualBox versions along with the Vagrant config file you use so I try to reproduce it?

Anyhow, I will publish the next version with the [latest keys](https://github.com/hashicorp/vagrant/blob/main/keys/vagrant.pub), seems like a bug in my build that it does not pick it up properly.

**Comment by civodul999** [comment]
Hi,
here the informations : 
```
OS : 20.04.6 LTS (Focal Fossa)
vagrant : Vagrant 2.2.6
virtualbox : Version 6.1.38_Ubuntu r153438
```

My version of openssh client is this one : 
`OpenSSH_8.2p1 Ubuntu-4ubuntu0.11, OpenSSL 1.1.1f  31 Mar 2020`

When I run `ssh-keygen`, the default key type is _rsa_, it seems with [a recent update](https://www.openssh.com/txt/release-9.5), it's now _ed25519_ but this version is not yet available on my OS.

**Comment by gusztavvargadr** [comment]
@civodul999 thanks for the details.

I have noticed that some of the tool versions you use are quite outdated. As a workaround, can you please try upgrading vagrant to `2.4.0` and VirtualBox to `6.1.48`. Those are the versions I also use for building and testing.

If this still does not work, I can try to publish a new version.

**Comment by civodul999** [comment]
@gusztavvargadr thank you very much !
After updating the packages like you said, it's ok now, I can connect on ubuntu22 with `vagrant` and also`molecule` software.

**Comment by gusztavvargadr** [comment]
@civodul999 that's great news, thanks for the update.
