### ISSUE TITLE
SSL Err no 54

### ISSUE THREAD

**Issue by rafaellucio** [gusztavvargadr/packer#45]
Hi, I have a problem, my download progress are 7.5Gb whem throw error SSL, do you help me please.

```bash
vagrant init gusztavvargadr/w16s-sql14d-vs15c; vagrant up --provider virtualbox
`Vagrantfile` already exists in this directory. Remove it before
running `vagrant init`.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'gusztavvargadr/w16s-sql14d-vs15c' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'gusztavvargadr/w16s-sql14d-vs15c'
    default: URL: https://atlas.hashicorp.com/gusztavvargadr/w16s-sql14d-vs15c
==> default: Adding box 'gusztavvargadr/w16s-sql14d-vs15c' (v0.4.0) for provider: virtualbox                              default: Downloading: https://atlas.hashicorp.com/gusztavvargadr/boxes/w16s-sql14d-vs15c/versions/0.4.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try again.
SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
```

Mac Sierra
iMac (21.5-inch, Late 2013)
Processor 2.7Hz Core i5 8GB DDR3

**Comment by gusztavvargadr** [comment]
@rafaellucio it might be a temporary connectivty and / or SSL setup issue on your end. Can you please try the suggestions mentioned here?

* https://github.com/test-kitchen/test-kitchen/issues/834
* https://github.com/Varying-Vagrant-Vagrants/VVV/issues/401

**Comment by gusztavvargadr** [comment]
@rafaellucio any news on this?

**Comment by derwasp** [comment]
@gusztavvargadr my 2 cents on this. When I tried using it on OSX as I told you last time, we had to restart the download process like 5 times till it worked.

**Comment by gusztavvargadr** [comment]
@derwasp thanks for sharing your experience, unfortunately I could not find a more reliable (and cheaper :) hosting option than Atlas yet. I noticed as well that sometimes it's less reliable.

@rafaellucio @derwasp as an alternative, if you have access to some more stable connection elsewhere, you can try to download the box file manually and transfer to another machine.

Just append `.json` to the Atlas box url, in this case like https://atlas.hashicorp.com/gusztavvargadr/boxes/w16s-sql14d-vs15c.json, where you can grab the direct link to the box file per version and provider. After downloading that, you can add it manually using [vagrant box add](https://www.vagrantup.com/docs/cli/box.html#add).

**Comment by derwasp** [comment]
@gusztavvargadr the point I was trying to make is that I think that OSX version of vagrant might behave differently. Even though it sounds odd.
I didn't have any issues in the Win machine.

**Comment by gusztavvargadr** [comment]
@rafaellucio @derwasp thanks for the help with the investigation, I'll close this for now as there is a workaround above and it seems to be a problem with Vagrant / Atlas itself, but let me know if you come across any other solution.
