### ISSUE TITLE
no access to files under shared folders with virtualbox 5.1.16

### ISSUE THREAD

**Issue by marcindulak** [gusztavvargadr/packer#46]
First, thanks for maintaining those boxes.

While the Vagrantfile below works properly with virtualbox 5.1.14, it fails with 5.1.16 with

```
==> windows: Get-Content : Cannot find path 'C:\vagrant\Vagrantfile' because it does not exist.
==> windows: At C:\tmp\vagrant-shell.ps1:1 char:1
==> windows: + Get-Content c:\vagrant\Vagrantfile
==> windows: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> windows:     + CategoryInfo          : ObjectNotFound: (C:\vagrant\Vagrantfile:String) [Get-Content], ItemNotFoundException
==> windows:     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# http://stackoverflow.com/questions/23926945/specify-headless-or-gui-from-command-line
def gui_enabled?
  !ENV.fetch('GUI', '').empty?
end

Vagrant.configure(2) do |config|
  config.vm.define "windows" do |machine|
    machine.vm.box = "gusztavvargadr/w16s"
    machine.vm.box_url = machine.vm.box
    machine.vm.provider 'virtualbox' do |v|
      v.gui = gui_enabled?
      v.memory = 1024  # Windows is greedy
      v.cpus = 1
    end
    machine.ssh.shell = "powershell"
  end
  config.vm.define "windows" do |machine|
    machine.vm.provision :shell, :inline => "ls c:\\vagrant"
    machine.vm.provision :shell, :inline => "Get-Content c:\\vagrant\\Vagrantfile"
  end
end

```

```
$ vboxmanage --version
5.1.16r113841
$ vagrant --version
Vagrant 1.9.2
$ uname -a
Linux ubuntu 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64
$ cat /etc/os-release | grep PRETTY
PRETTY_NAME="Ubuntu 16.04.2 LTS"

```

**Comment by gusztavvargadr** [comment]
@marcindulak thanks for reporting the issue.

I remember I had problems with `5.1.16` when building the boxes on Windows as well, that's why I've built with `5.1.14` instead (that's also the version of the guest additions in the box).

Is downgrading VirtualBox an option for you temporarily? Or maybe could also check for upgrading the guest additions to `5.1.16` as well and [repackaging with Vagrant itself](https://www.vagrantup.com/docs/cli/package.html).

I plan to rebuild these boxes regularly with the latest updates and will try the next VirtualBox patch when it's available, for now unfortunately I don't have the build capacity to maintain mutlitple versions at the same time.

**Comment by marcindulak** [comment]
The guest additions version seems to be 5.1.2, as reported by `vboxmanage guestproperty enumerate <uuid|vmname>`, and updating guest additions is not working on the command line from Linux https://forums.virtualbox.org/viewtopic.php?f=7&t=73868 - I can't do that in the GUI due to limited resources.

I have the same "Cannot find path" problem with virtualbox 5.1.16 and https://atlas.hashicorp.com/opentable/boxes/win-2012r2-standard-amd64-nocm , that one has guest additions 4.3.12, and for https://atlas.hashicorp.com/mwrock/boxes/Windows2012R2 guest additions 5.1.2, so the problem is present not only for your windows boxes.

We need to figure out first which components are responsible for the problem.
Can you try to verify if building with 5.1.16 solves the problem just for this single box?
No need to publish it now, I can use virtualbox 5.1.14.
  
If the problem is due to something in Virtualbox itself then it needs to be reported at https://www.virtualbox.org/wiki/Bugtracker otherwise at packer/vagrant/...

**Comment by gusztavvargadr** [comment]
@marcindulak thanks for the details.

You're right, I've double checked, [this uses 5.1.2](https://github.com/gusztavvargadr/chef/blob/0.1.0/cookbooks/gusztavvargadr_windows/attributes/default.rb#L8-L10). I'll try to build it with the latest and get back to you.

**Comment by gusztavvargadr** [comment]
@marcindulak ok I can confirm the issue. I've built with the latest `5.1.16` guest additions and it complains as you describe.

I've found this, they also recommend the downgrade: https://github.com/mitchellh/vagrant/issues/8222

I'll close this and hope it works again in the future at some point with the actual latest patches :)

Thanks for the help with the investigation.

**Comment by gusztavvargadr** [comment]
@marcindulak FYI the latest 5.1.18 seems to fix the issue https://github.com/mitchellh/vagrant/issues/8352#issuecomment-286987144
