### ISSUE TITLE
verify the presence of box checksums

### ISSUE THREAD

**Issue by marcindulak** [gusztavvargadr/packer#74]
curl https://app.vagrantup.com/gusztavvargadr/boxes/w10e-vs17c | python3 -m json.tool  | grep checksum

https://groups.google.com/forum/#!topic/vagrant-up/V0E4PAajM-g

**Comment by gusztavvargadr** [comment]
@marcindulak sorry, I'm not sure what is your point here, can you be a bit more specific please?

**Comment by marcindulak** [comment]
Since you are one of the few maintainers of vagrant boxes on app.vagrantup.com who try to keep their boxes in a good shape I thought you will be interested in the checksum problem, discovered recently https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878759

I don't think we need to do anything about this now, but it's good to follow this issue and if vagrant comes up with a solution, adapt the boxes. Basically the debian developers discovered that the following command is not failing:

```
$ vagrant box add --checksum-type sha256 --checksum 1234 --provider virtualbox gusztavvargadr/w10e-vs17c
==> box: Loading metadata for box 'gusztavvargadr/w10e-vs17c'
    box: URL: https://vagrantcloud.com/gusztavvargadr/w10e-vs17c
==> box: Adding box 'gusztavvargadr/w10e-vs17c' (v0.8.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/gusztavvargadr/boxes/w10e-vs17c/versions/0.8.0/providers/virtualbox.box
==> box: Successfully added box 'gusztavvargadr/w10e-vs17c' (v0.8.0) for 'virtualbox'!
```

**Comment by gusztavvargadr** [comment]
@marcindulak thanks for the suggestion and the details, I'll check this for the the upcoming releases. If you have any more information or suggestions later, please let me know.

Indeed, I try to publish boxes of a quality which I'd expected from other publish boxes as well :) Please let me know if you miss a box you'd need or you notice anything in general which could be improved. Thanks!

**Comment by gusztavvargadr** [comment]
@marcindulak FYI I have started publishing box checksums as Vagrant Cloud seems to have support it for now. Not visible on the UI yet and not sure if the Vagrant client already verifies these, but if you think, the JSON version of the boxes contain the information already, like:

https://app.vagrantup.com/gusztavvargadr/boxes/windows-server.json

I'm closing this now but please let me know if there's anything else I can do for this.
