### ISSUE TITLE
SQL Server feature: Reporting Services

### ISSUE THREAD

**Issue by DannyMeister** [gusztavvargadr/packer#79]
I'm not so sure whether there's enough demand for Reporting Services to be pre-installed on the boxes, but one of the applications I work on requires it.

While you can install Reporting Services separately, so technically I have an avenue to resolve this even without it being on the base box, requiring the full SQL Server installation media is certainly more than i'd want in my vagrant provisioning.

**Comment by gusztavvargadr** [comment]
@DannyMeister would a setup with a separate box with only the reporting services components work for you or you'd like to have this together with the core engine? Just asking what would you prefer for your development scenario. Not sure on the timing yet when could I have it published, but at least I could get you some hints how to build it yourself.

**Comment by DannyMeister** [comment]
Oops, that's me signed into a different account.

**Comment by gusztavvargadr** [comment]
@DannyMeister ok, thanks, do you have a preference of version as well? 2014 or 2017 instead? For 2017 it seems to be a standalone installer now (like SSMS), that's also doable, but would take some more time probably.

**Comment by DannyMeister** [comment]
While I would eventually need both, 2014 would be most immediately helpful, as it would mean being able to use this box for all versions of our software. Thanks!

**Comment by gusztavvargadr** [comment]
@DannyMeister sorry for missing this so far, if you're still in need for this, I can try include it in the next release.

Just curious, where do you stand on containerizing some of these workloads? E.g. first separating the images so that you have only the server components, SSMS and the rest on the host or in other VMs, then having the servers with Docker (even on Linux ;)

I'm not really using these boxes any more myself, but I'm glad to maintain them for a while, please let me know if there are any possible improvements.

**Comment by DannyMeister** [comment]
Still have a need for this, and in the meantime I've just been doing more manual setup in Virtual Box with a base image I have instead of vagrant.  Need to get back into the automation game. :)

I installed Reporting Services for SQL Server 2017 a single time on my base image with the following Powershell snippet.


```
$extraproducts = @(
	[pscustomobject]@{
		url="https://download.microsoft.com/download/E/6/4/E6477A2A-9B58-40F7-8AD6-62BB8491EA78/SQLServerReportingServices.exe";
		parameters="/norestart /passive /IAcceptLicenseTerms /Edition=Dev";
		name="SQLServerReportingServices.exe"
	}
)

# other code removed for brevity

foreach($product in $extraproducts)
{
	$command = [Environment]::GetFolderPath("MyDocuments") + '\' + $product.name
	$parameters = $product.parameters
	(New-Object System.Net.WebClient).DownloadFile($product.url, $command);
	Start-Process $command $parameters -Wait
	Remove-Item $command
}
```


We are beginning to look into containerizing what we can, and also a transition to some of the more cloud friendly technologies like Cosmos rather than SQL Server.  I think we can get some of the external dependencies moved over, but we have a decent number of 20 year old components using API's and Windows OS features not available on Windows Server Core, therefore not available in Docker.

**Comment by gusztavvargadr** [comment]
@DannyMeister thanks for the snippet, I'll give it a go soon.

I am planning to discontinue Windows Server 2016 builds, would you mind an upgrade to Windows Server 2019? Also, do you still need SQL Server 2014 as well?

**Comment by DannyMeister** [comment]
I'm good with upgrading OS and SQL Server.
