### ISSUE TITLE
Windows update inside gusztavvargadr/w10e-vs17c

### ISSUE THREAD

**Issue by tmm1** [gusztavvargadr/packer#80]
I'm having a lot of problems getting Windows Update to work (error 0x800040002). Is there a known fix?

**Comment by gusztavvargadr** [comment]
@tmm1 All my boxes have Windows Updates disabled by design. Can you try to enable the service and try running updates after it? Please let me know.

**Comment by gusztavvargadr** [comment]
@tmm1 please reopen know if you need further help with this.
