### ISSUE TITLE
Update to Windows 10 version 1809

### ISSUE THREAD

**Issue by gusztavvargadr** [gusztavvargadr/packer#97]
https://support.microsoft.com/en-us/help/4464619/windows-10-update-history

**Comment by TonyApuzzo** [comment]
This version (1809.0.0) doesn't seem to work with shell provisioning anymore.  My before launching the powershell script vagrant hangs in SCP forever.  When I manually shutdown the image, Vagrant thinks nothing happened and destroys  the image -- thus leading to infinite loop.

Here is the Vagrantfile:
https://gist.github.com/TonyApuzzo/a56763310821fc2a9826664400ded9cb

Both the latest w10e and w16s fail the same way.

**Comment by gusztavvargadr** [comment]
@TonyApuzzo thanks for the feedback and sorry about the issues.

This version has not been published (with Windows 1809), but the 1809.0.0 boxes has been updated to use SSH instead of WinRM, might be the root cause?

Can you try do set the shell explicitly like here?

https://github.com/gusztavvargadr/packer/blob/1d7a5161e11e6d2151210a775e678ade3f51f3cb/src/w/packer/postprocessors/vagrant-virtualbox/Vagrantfile#L4

**Comment by TonyApuzzo** [comment]
Oops sorry about the version confusion.  Yes, the 1809.0.0 release.

Windows 10 Pro Workstation, build 17134
Vagrant 2.2.0
Virtualbox 5.2.22

Changing to explicit powershell causes an timeout instead of unnoticed implicit hang:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'gusztavvargadr/w10e'...

Progress: 10%
Progress: 90%
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'gusztavvargadr/w10e' is up to date...
==> default: Setting the name of the VM: w10e
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 33389 (host) (adapter 1)
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
ERROR warden: Error occurred: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.
If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.
```

**Comment by gusztavvargadr** [comment]
@TonyApuzzo thanks for the details. I can confirm the issue, most probably caused by #91, though I could not find a fix yet. Will try to revert back to WinRM by default in #101, seems to be more stable than SSH atm.

In the meantime, as a workaround, as your great Vagrant setup also shows, 1808 can be a good option. Also, I could not reproduce the issue with Hyper-V, to me it occurred with VirtualBox only, if another provider is an option for you.
